swagger: '2.0'
info:
  description: Swagger Spec for the Nuapay TPP OpenBanking/PSD2. Provides AISP Endpoints
  version: '1.6.0'
  title: Nuapay TPP AISP API Specification
  contact:
    name: Nuapay
    email: 'api.support@nuapay.com'
  license:
    name: 'Nuapay'
    url: 'https://sentenial.com'
  x-logo:
    backgroundColor: '#FFFFFF'
    url: 'https://www.nuapay.com/wp-content/uploads/2018/04/nuapay.svg'
host: 'api.nuapay.com'
basePath: /tpp
schemes: 
  - https
tags:
  - name: Bank Service
    description: |-
      Bank endpoints allow a merchant to,
      - Retrieve a list of banks that support the Open Banking scheme
      - View details of a specific bank that supports the Open Banking scheme
  - name: AISP Consent Management Service
    description: |-
      The Account Information endpoints allow you to,
      - Request consent from a PSU for access to his/her account(s), balance(s) and transactions.
      - Retrieve the account details to which the PSU has granted consent.
      - Revoke the account access consent.
      - Handle the account access ASPSP callback, if you are using the SELF_HOSTED_CALLBACK integration type
      
      To initiate the consent you will need your client's account-holding bank details (the PSU's ASPSP). Use the Get Banks service to list the ASPSPs supported by the TPP. Please find the service specification under https://sentenial.github.io/open-banking-swagger/docs/redoc.html#tag/Bank-Service
  - name: AISP Account Information Read Service
    description: |-
      The Account Information Read endpoints allow you to:
      - List Accounts
      - Read Account Details
      - Retrieve Account Balances
      - Retrieve Account Transactions
paths:
  /accounts:
    get:
      tags:
        - AISP Account Information Read Service
      summary: List  accounts under granted access permissions.
      description: List PSU Accounts
      operationId: listPSUAccountsUsingGET
      security:
        - MerchantOAuth2:
          - openbanking_aisp
          - openbanking_aisp_read
        - MerchantApiKey: []
  /bankfamilies:
    get:
      tags:
        - Bank Service
      summary: View Bank Families
      description: Get list of Bank Families
      operationId: getBankFamiliesUsingGET
      security:
        - MerchantOAuth2:
          - openbanking_aisp
        - MerchantApiKey: []
        - PartnerOAuth2:
          - openbanking_aisp
        - PartnerApiKey: []
  /bankfamilies/{bankfamilyId}:
    get:
      tags:
        - Bank Service
      summary: View Bank Family
      description: View Bank Family Details
      operationId: getBankFamilyUsingGET
      security:
        - MerchantOAuth2:
          - openbanking_aisp
        - MerchantApiKey: []
        - PartnerOAuth2:
          - openbanking_aisp
        - PartnerApiKey: [] 
  /banks:
    get:
      tags:
        - Bank Service
      summary: Retrieve Banks
      description: Get Supported Banks On This TPP
      operationId: getBanksUsingGET
      security:
        - MerchantOAuth2:
          - openbanking_aisp
        - MerchantApiKey: []
        - PartnerOAuth2:
          - openbanking_aisp
        - PartnerApiKey: []
  /banks/{bankId}:
    get:
      tags:
        - Bank Service
      summary: View Bank
      description: View Bank Details
      operationId: getBankUsingGET
      security:
        - MerchantOAuth2:
          - openbanking_aisp
        - MerchantApiKey: []
        - PartnerOAuth2:
          - openbanking_aisp
        - PartnerApiKey: []
  /consents:
    post:
      tags:
        - AISP Consent Management Service
      summary: Create Account Information Access Consent
      description: Create an account consent request POST endpoint
      operationId: createAccountConsentUsingPOST
      security:
        - MerchantOAuth2:
          - openbanking_aisp
        - MerchantApiKey: []
  /consents/callback:
    post:
      tags:
        - AISP Consent Management Service
      summary: Forward Accounts Access Consent Callback
      description: Forward  Accounts Access Consent Callback POST endpoint
      operationId: forwardAccountAccessConsentCallbackPOST
      security:
        - MerchantOAuth2:
          - openbanking_aisp_callback
        - PartnerOAuth2:
          - openbanking_aisp_callback
        - SystemOAuth2:
          - openbanking_aisp_callback
  /consents/{consentId}:
    patch:
      tags:
      - AISP Consent Management Service
      summary: Set Bank Id and Submit 
      description: Set Bank Id and Submit
      operationId: setBankIdForConsentUsingPATCH
      security:
        - MerchantOAuth2:
          - openbanking_aisp
        - MerchantApiKey: []
    get:
      tags:
        - AISP Consent Management Service
      summary: Retrieve Account Access Consent Details
      description: GET account access consent details endpoint
      operationId: getAccountConsentUsingGET
      security:
        - MerchantOAuth2:
          - openbanking_aisp
          - openbanking_aisp_read
        - MerchantApiKey: []
  /consents/{consentId}/revoke:
    post:
      tags:
        - AISP Consent Management Service
      summary: Revoke Account Access Consent
      description: Revoke account access consent endpoint
      operationId: revokeAccountConsentUsingPOST
      security:
        - MerchantOAuth2:
          - openbanking_aisp
        - MerchantApiKey: []
securityDefinitions:
  MerchantApiKey:
    type: basic
  PartnerApiKey:
    type: basic
  MerchantOAuth2:
    type: oauth2
    tokenUrl: https://api.nuapay.com/oauth/token_key
    flow: password
    scopes:
      openbanking_aisp: Account Information Service Provider access
      openbanking_aisp_read: Account Information Service Provider read access
      openbanking_aisp_callback: Open Banking AISP callback forwarding access
  PartnerOAuth2:
    type: oauth2
    tokenUrl: https://api.nuapay.com/oauth/token_key
    flow: password
    scopes:
      openbanking_aisp: Account Information Service Provider access
      openbanking_aisp_read: Account Information Service Provider read access
      openbanking_aisp_callback: Open Banking AISP callback forwarding access
  SystemOAuth2:
    type: oauth2
    tokenUrl: https://api.nuapay.com/oauth/token_key
    flow: password
    scopes:
      openbanking_aisp: Account Information Service Provider access
      openbanking_aisp_read: Account Information Service Provider read access
      openbanking_aisp_callback: Open Banking AISP callback forwarding access